name: Build
on:
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag or PR number to deploy'
        required: true
jobs:
  docker-sotbisrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildkit-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GR_TOKEN }}
      - name: Build & push server docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: |
            ghcr.io/cotbu/notifier:${{ github.event.pull_request.number || github.event.inputs.tag }}

#      - name: Send telegram message after building image from PR
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_CHANNEL }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            🔍PR #${{github.event.number}}:
#            Image built successfully
#            Run by ${{ github.triggering_actor }}
#
#            See changes: https://github.com/${{ github.repository }}/pull/${{github.event.number}}
