version: "3"

services:
  redpanda:
    image: "docker.io/vectorized/redpanda:latest"
    ports:
      - "9092:9092"

  notifier:
    hostname: notifier
    image: "ghcr.io/cotbu/notifier:${tag}"
    volumes:
      - /root/config:/app/config
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - energy
    restart: unless-stopped
