name: Dev Deploy
on:
  push:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag or PR number to deploy'
        required: false
jobs:
  docker-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildkit-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildkit-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build & push server docker
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: Dockerfile
#          platforms: linux/amd64
#          cache-from: type=local,src=/tmp/.buildx-cache
#          cache-to: type=local,dest=/tmp/.buildx-cache
#          push: true
#          tags: |
#            ghcr.io/cotbu/notifier:${{ github.event.pull_request.number || github.event.inputs.tag || 'latest' }}
      - name: Webhook to reload docker
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ vars.WEBHOOK_URL }}/reload-backend?tag=${{ github.event.pull_request.number || github.event.inputs.tag || 'latest' }}&image=notifier
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
#      - name: Send telegram message after develop push
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_CHANNEL }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            ${{ github.actor }} pushed commits to 🛠develop:
#            Last commit message: ${{ github.event.commits[0].message }}
#
#            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
